# Stage 1: Build the app with webpack
FROM node:18.15.0-alpine AS build
# Set the working directory to /app
WORKDIR /app 
# Copy package.json and package-lock.json to /app
COPY package*.json .
# Install dependencies with npm ci
RUN npm install
# Copy the rest of the application code to /app
COPY . .
# Start the server
CMD ["npm", "start"]
